import { createSlice } from '@reduxjs/toolkit';

const initialState = {
  count: 0,
};

const counterSlice = createSlice({
  name: 'counter',
  initialState,
  reducers: {
    increment: (state) => {
      state.count += 1;
    },
    decrement: (state) => {
        state.count -= 1;
    },
    reset: (state) => {
        state.count = 0;
    },

    },
  });

  // Export the actions generated by createSlice
export const { increment, decrement, reset } = counterSlice.actions;
// Export the reducer to be used in the store
export default counterSlice.reducer;
